// client/src/utils/dummyData.js
// Sample goals for development/demo. Remove in production.

import { GOAL_STATUS } from '../constants/goals';

export const DUMMY_GOALS = [
  {
    id:          'goal_001',
    title:       'Reduce deployment failures by 40%',
    description: 'Improve CI/CD pipeline reliability and reduce failed deployments through better test coverage, rollback strategies, and release gates.',
    thrustArea:  'Engineering Excellence',
    unit:        'Percentage',
    target:      '40',
    weightage:   '25',
    status:      GOAL_STATUS.APPROVED,
    createdAt:   '2024-04-01T09:00:00Z',
    updatedAt:   '2024-04-05T11:30:00Z',
    managerComment: 'Good target. Make sure to track per-sprint.',
    isShared:    false,
  },
  {
    id:          'goal_002',
    title:       'Improve API response time to under 200ms',
    description: 'Optimise database queries, add caching layers, and refactor slow endpoints to achieve sub-200ms p95 response time.',
    thrustArea:  'Engineering Excellence',
    unit:        'Numeric',
    target:      '200',
    weightage:   '20',
    status:      GOAL_STATUS.APPROVED,
    createdAt:   '2024-04-01T09:10:00Z',
    updatedAt:   '2024-04-05T11:30:00Z',
    managerComment: '',
    isShared:    false,
  },
  {
    id:          'goal_003',
    title:       'Achieve 90% customer CSAT score',
    description: 'Improve customer satisfaction through faster support resolution, better onboarding, and proactive communication.',
    thrustArea:  'Customer Centricity',
    unit:        'Percentage',
    target:      '90',
    weightage:   '20',
    status:      GOAL_STATUS.LOCKED,
    createdAt:   '2024-04-01T09:20:00Z',
    updatedAt:   '2024-04-06T10:00:00Z',
    managerComment: 'Locked after final approval.',
    isShared:    true,
  },
  {
    id:          'goal_004',
    title:       'Complete security compliance audit',
    description: 'Ensure all systems pass the annual ISO 27001 security audit with zero critical findings.',
    thrustArea:  'Risk Management',
    unit:        'Timeline',
    target:      'Q3 2024',
    weightage:   '20',
    status:      GOAL_STATUS.REWORK_REQUESTED,
    createdAt:   '2024-04-01T09:30:00Z',
    updatedAt:   '2024-04-07T14:00:00Z',
    managerComment: 'Please add specific sub-milestones and owners.',
    isShared:    false,
  },
  {
    id:          'goal_005',
    title:       'Zero critical production incidents',
    description: 'Maintain zero Sev-1 production incidents through better monitoring, on-call protocols, and incident runbooks.',
    thrustArea:  'Operational Excellence',
    unit:        'Zero-based',
    target:      '0',
    weightage:   '15',
    status:      GOAL_STATUS.DRAFT,
    createdAt:   '2024-04-10T08:00:00Z',
    updatedAt:   '2024-04-10T08:00:00Z',
    managerComment: '',
    isShared:    false,
  },
];
